version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: npx chromatic --project-token=2wix88i1ziu
      - run: |
          if [ $CIRCLE_BRANCH = "master" ]
          then
            yarn release
          fi
